version: "3"

services:
   
   sql:
      build: ./sql
      volumes:
         - peep:/var/lib/mysql
      env_file:
         - ./docker-compose.env

   php:
      build: ./php
      depends_on:
         - sql
      env_file:
         - ./docker-compose.env
      ports:
         - 8081:80
      volumes:
         - ./php/Classes:/var/www/Classes
         - ./php/public_html:/var/www/public_html
         - ./php/lib:/var/www/lib

   app:
      build: ./app/node_modules
      depends_on:
         - php
      ports:
         - 8080:80
      volumes:
        - ./app/:/app/
        - ./app/node_modules:/app/node_modules/

volumes:
   peep:
